package server.api;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import server.services.RandomGeneratorService;

@RestController
@RequestMapping("/api/admin")
public class AdminController {

    @Autowired
    private RandomGeneratorService randomGenerator;

    /**
     * checks if the password given by user is equal to the admin password generated by the server
     *
     * @param password input password of user
     * @return success response if password given by user is correct, else bad request
     */
    @PostMapping(path = {"", "/"})
    public ResponseEntity<String> adminLogin(@RequestBody String password) {
        if (randomGenerator.validatePassword(password)) {
            return ResponseEntity.ok().build();
        }
        return ResponseEntity.badRequest().build();
    }


}
